### ISSUE TITLE
Approval to download the dataset

### ISSUE THREAD

**Issue by Duckkkkky** [hassony2/obman#15]
Hi hassony2, thanks for the great data!
I have sent a few e-mails but didn't receive any replies about the download link yet. I wonder if you have received the requests or not.

**Comment by Duckkkkky** [comment]
Hello? Is anyone here?

**Comment by Duckkkkky** [comment]
Hello?

**Comment by hassony2** [comment]
Hello :)
Sorry about that, this problem is due to my academic account having gotten deactivated.
For now, you can get access to the dataset by first accepting the license at https://www.di.ens.fr/willow/research/obman/data/requestaccess.php and then sending an e-mail to yana.hasson.inria@gmail.com **with "ObMan data request" as subject**.

Following these two steps you will shortly receive an email with the instruction to download the data. Sorry about the inconvenience.

Let me know if you run into any trouble after having sent the email.

Have a great day !

**Comment by Duckkkkky** [comment]
Have got the dataset. Thanks a lot for reply :)
