### ISSUE TITLE
About 'modelnet_meshes_***'  in samplemesh.py 

### ISSUE THREAD

**Issue by swanilee** [hassony2/obman#7]
First, thank you for a chance to study about this code.

 I run shapenet_cache.py and shapenet_samplepoint.py to train traineval.py in obman_train.
But, running the shapenet_samplepoints.py , i saw this error code.

"
Loaded /home/bella/obman_train/datasymlinks/ShapeNetCore.v2/03593526/10af6bdfd126209faaf0ad030fc37d94/models/model_normalized.pkl
Traceback (most recent call last):
  File "shapenet_samplepoints.py", line 49, in create_ray_samples
    points = sample_mesh(mesh, min_hits=min_hits)
  File "/home/bella/obman_dir/obman/samplemesh.py", line 80, in sample_mesh
    raise Exception('Exceeded {} attempts'.format(interrupt))
Exception: Exceeded 10 attempts
"

The shapnet_samplepoints.py stopped at 1007/3036.
To solve this problem, i saw the samplemesh.py, then i don't know about this " modelnet_meshes_***~".

"
model_path = ('/sequoia/data2/yhasson/datasets/'
                  'modelnet_meshes_2018_10_02/glass_000001702_12.obj')
    model_path = ('/sequoia/data2/yhasson/datasets/'
                  'modelnet_meshes_2018_10_02/bottle_000001910_21.obj')
" in samplemesh.py.

I don't know how i solve this problem.
Thank you for reading my question :)

**Comment by hassony2** [comment]
Hi @swanilee 

This error usually happens if your object is not correctly centered and scaled (which depends on each dataset).
The object should be centered in a sphere of size 1 in order for the sampling to work.

The first step is to investigate which object raises this error.
This could be done by wrapping the faulty line 

[points = sample_mesh(mesh, min_hits=min_hits)](https://github.com/hassony2/obman/blob/7404e33e341985b27a6bf32c547e79e9574c78da/shapenet_samplepoints.py#L46) 

line in a try: ... except Exception: print(sample_path) statement to find which object is problematic, and then loading it for instance in [meshlab](https://www.meshlab.net/) to see what might be causing this error.


Best !

Yana

**Comment by swanilee** [comment]
Thank you for answering!! :) :+1:
